-- Run this in Supabase SQL Editor.
create table if not exists public.prank_visits (
  id bigint generated by default as identity primary key,
  opened_at timestamptz not null default now(),
  session_key text unique,
  visitor_key text not null,
  device_type text,
  browser text,
  screen_size text,
  referrer text,
  user_agent text,
  session_seconds integer default 0,
  reveal_reached boolean default false,
  visitor_message text,
  message_sent_at timestamptz
);

alter table public.prank_visits enable row level security;

-- Public visitors may create a basic anonymous visit record.
create policy "public can insert prank visits"
on public.prank_visits for insert
to anon
with check (true);

-- Public visitors may update only their session row through the returned row ID.
-- This policy is intentionally permissive for a small prank project.
create policy "public can update prank visits"
on public.prank_visits for update
to anon
using (true)
with check (true);

-- Only authenticated admin can read analytics.
create policy "authenticated admin can read"
on public.prank_visits for select
to authenticated
using (auth.jwt() ->> 'email' = 'mohitkumar6396105@gmail.com');

-- Authenticated admin may delete records if needed.
create policy "authenticated admin can delete"
on public.prank_visits for delete
to authenticated
using (auth.jwt() ->> 'email' = 'mohitkumar6396105@gmail.com');

-- Run these lines too if the table already existed before this update.
alter table public.prank_visits add column if not exists visitor_message text;
alter table public.prank_visits add column if not exists message_sent_at timestamptz;

-- Required for message/session updates without exposing visitor rows.
alter table public.prank_visits add column if not exists session_key text;
create unique index if not exists prank_visits_session_key_idx on public.prank_visits(session_key);
